NAME	:=	libft.a
BNAME	:=	libft.a
SRCS	=	ft_memset.c ft_memcpy.c ft_memmove.c ft_memchr.c ft_memcmp.c\
			ft_memalloc.c ft_memdel.c ft_memccpy.c ft_strlcpy.c ft_strlen.c\
			ft_strdup.c ft_strcat.c ft_strlcat.c ft_strstr.c ft_strncmp.c\
			ft_strnew.c ft_strdel.c ft_strclr.c ft_striter.c ft_strmap.c\
			ft_strmapi.c ft_substr.c ft_strjoin.c ft_strtrim.c ft_strrchr.c\
			ft_isalpha.c ft_isdigit.c ft_isalnum.c ft_isascii.c ft_isprint.c\
			ft_isset.c ft_putchar_fd.c ft_putstr_fd.c ft_putnbr_fd.c\
			ft_putendl_fd.c  ft_bzero.c ft_calloc.c ft_atoi.c ft_strchr.c\
			ft_toupper.c ft_tolower.c ft_split.c ft_itoa.c ft_strnstr.c
OBJS	=	$(SRCS:.c=.o)
BONUS	=	ft_lstnew_bonus.c ft_lstadd_front_bonus.c ft_lstsize_bonus.c\
			ft_lstlast_bonus.c ft_lstadd_back_bonus.c ft_lstdelone_bonus.c\
			ft_lstclear_bonus.c ft_lstiter_bonus.c ft_lstmap_bonus.c
BOBJS	=	$(BONUS:.c=.o)
HEADER	=	libft.h

CC 		=	gcc
CFLAGS	=	-Wall -Werror -Wextra -c
OPTIONS = 	ar rc
RM		=	rm -f



all:		$(NAME)

$(NAME):
			$(CC) $(CFLAGS) $(SRCS)
			$(OPTIONS) $(NAME) $(OBJS)

bonus:
			$(CC) $(CFLAGS) $(SRCS) $(BONUS)
			$(OPTIONS) $(BNAME) $(OBJS) $(BOBJS) 

clean:
			$(RM) $(OBJS) ${BOBJS}

fclean: 	clean
			$(RM) $(NAME)

re:			fclean all

.PHONY: all clean fclean re bonus
